const List<Map<String, dynamic>> photographers = [
  {
    'title': 'Click N Weds',
    'name': 'Rachit Naik',
    'desc':
        'Expert Indian wedding photography capturing every magical moment with a blend of traditional elegance and modern creativity',
    'avatar': 'https://via.placeholder.com/150',
    'rating': 4,
    'location': 'Hyderabad, Telangana',
    'experience': '500+ cities',
    'avialability': '7+ cities',
    'mainimage': 'https://via.placeholder.com/150',
    'image1': 'https://via.placeholder.com/150',
    'image2': 'https://via.placeholder.com/150',
    'image3': 'https://via.placeholder.com/150',
    'image4': 'https://via.placeholder.com/150',
    'image5': 'https://via.placeholder.com/150',
  },
  {
    'title': 'Be a Groom',
    'name': 'John Doe',
    'desc':
        'Expert Indian wedding photography capturing every magical moment with a blend of traditional elegance and modern creativity',
    'avatar': 'https://via.placeholder.com/150',
    'rating': 5,
    'location': 'Mumbai, Maharashtra',
    'experience': '700+ cities',
    'avialability': '9+ cities',
    'mainimage': 'https://via.placeholder.com/150',
    'image1': 'https://via.placeholder.com/150',
    'image2': 'https://via.placeholder.com/150',
    'image3': 'https://via.placeholder.com/150',
    'image4': 'https://via.placeholder.com/150',
    'image5': 'https://via.placeholder.com/150',
  },
  {
    'title': 'Only Weds',
    'name': 'Rhythm Midha',
    'desc':
        'Expert Indian wedding photography capturing every magical moment with a blend of traditional elegance and modern creativity',
    'avatar': 'https://via.placeholder.com/150',
    'rating': 4,
    'location': 'Haryana, Delhi',
    'experience': '400+ cities',
    'avialability': '5+ cities',
    'mainimage': 'https://via.placeholder.com/150',
    'image1': 'https://via.placeholder.com/150',
    'image2': 'https://via.placeholder.com/150',
    'image3': 'https://via.placeholder.com/150',
    'image4': 'https://via.placeholder.com/150',
    'image5': 'https://via.placeholder.com/150',
  },
  {
    'title': 'Click N Weds',
    'name': 'Rachit Naik',
    'desc':
        'Expert Indian wedding photography capturing every magical moment with a blend of traditional elegance and modern creativity',
    'avatar': 'https://via.placeholder.com/150',
    'rating': 4,
    'location': 'Hyderabad, Telangana',
    'experience': '500+ cities',
    'avialability': '7+ cities',
    'mainimage': 'https://via.placeholder.com/150',
    'image1': 'https://via.placeholder.com/150',
    'image2': 'https://via.placeholder.com/150',
    'image3': 'https://via.placeholder.com/150',
    'image4': 'https://via.placeholder.com/150',
    'image5': 'https://via.placeholder.com/150',
  },
  {
    'title': 'Click N Weds',
    'name': 'Rachit Naik',
    'desc':
        'Expert Indian wedding photography capturing every magical moment with a blend of traditional elegance and modern creativity',
    'avatar': 'https://via.placeholder.com/150',
    'rating': 4,
    'location': 'Hyderabad, Telangana',
    'experience': '500+ cities',
    'avialability': '7+ cities',
    'mainimage': 'https://via.placeholder.com/150',
    'image1': 'https://via.placeholder.com/150',
    'image2': 'https://via.placeholder.com/150',
    'image3': 'https://via.placeholder.com/150',
    'image4': 'https://via.placeholder.com/150',
    'image5': 'https://via.placeholder.com/150',
  },
];
