// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi2e_zgaojNypt4m6q9do5jROG8zeLoQg',
    appId: '1:554088293215:android:d9aa04c8581f8229f8ccea',
    messagingSenderId: '554088293215',
    projectId: 'wedding-ab7f0',
    storageBucket: 'wedding-ab7f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAeYe6f3KorpWUSzv1OjdtDIDt-7_E2Cw',
    appId: '1:554088293215:ios:ea0fb767717edca6f8ccea',
    messagingSenderId: '554088293215',
    projectId: 'wedding-ab7f0',
    storageBucket: 'wedding-ab7f0.appspot.com',
    androidClientId: '554088293215-pto2tods2do2tuc5e6f0vrbce52da238.apps.googleusercontent.com',
    iosClientId: '554088293215-8j11aua4h6fivkgckhu13taa0n5m6cfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.wedding',
  );

}